---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: openstack-neutron-operator-manager-role
rules:
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - projects/status
  verbs:
  - get
- apiGroups:
  - neutron.openstack.ics.cloud
  resources:
  - rbacpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.ics.cloud
  resources:
  - rbacpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - neutron.openstack.ics.cloud
  resources:
  - rbacpolicies/status
  verbs:
  - get
  - patch
  - update
