---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ics-operators-manager-role
rules:
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - keypairs
  - keypairs/finalizers
  - keypairs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - users
  - users/finalizers
  - users/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - groups
  - groups/finalizers
  - groups/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - projects
  - projects/finalizers
  - projects/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.ics.cloud
  resources:
  - users
  - users/finalizers
  - users/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neutron.openstack.ics.cloud
  resources:
  - rbacpolicies
  - rbacpolicies/finalizers
  - rbacpolicies/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
