---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ceph-admin-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - keypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - keypairs/finalizers
  verbs:
  - update
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - keypairs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - admin.ceph.ics.cloud
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
